"""add_user_online_status_table

Revision ID: d0316d20450f
Revises: caea13ae7c96
Create Date: 2025-09-11 09:02:57.562596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0316d20450f'
down_revision = 'caea13ae7c96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_online_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_online_status_is_online', 'user_online_status', ['is_online'], unique=False)
    op.create_index('idx_user_online_status_last_activity', 'user_online_status', ['last_activity'], unique=False)
    op.create_index('idx_user_online_status_session_id', 'user_online_status', ['session_id'], unique=False)
    op.create_index('idx_user_online_status_tenant_id', 'user_online_status', ['tenant_id'], unique=False)
    op.create_index('idx_user_online_status_tenant_online', 'user_online_status', ['tenant_id', 'is_online'], unique=False)
    op.create_index('idx_user_online_status_user_id', 'user_online_status', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_online_status_user_id', table_name='user_online_status')
    op.drop_index('idx_user_online_status_tenant_online', table_name='user_online_status')
    op.drop_index('idx_user_online_status_tenant_id', table_name='user_online_status')
    op.drop_index('idx_user_online_status_session_id', table_name='user_online_status')
    op.drop_index('idx_user_online_status_last_activity', table_name='user_online_status')
    op.drop_index('idx_user_online_status_is_online', table_name='user_online_status')
    op.drop_table('user_online_status')
    # ### end Alembic commands ###