"""Add subscription history table

Revision ID: eeb4c0235184
Revises: 4eff1025411c
Create Date: 2025-09-08 22:21:20.655375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eeb4c0235184'
down_revision = '4eff1025411c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_log_ip', table_name='activity_logs')
    op.drop_index('idx_activity_log_status', table_name='activity_logs')
    op.drop_index('idx_activity_log_tenant_action', table_name='activity_logs')
    op.drop_index('idx_activity_log_tenant_date', table_name='activity_logs')
    op.drop_index('idx_activity_log_tenant_resource', table_name='activity_logs')
    op.drop_index('idx_activity_log_tenant_user', table_name='activity_logs')
    op.drop_index('ix_activity_logs_action', table_name='activity_logs')
    op.drop_index('ix_activity_logs_resource_id', table_name='activity_logs')
    op.drop_index('ix_activity_logs_resource_type', table_name='activity_logs')
    op.drop_index('ix_activity_logs_tenant_id', table_name='activity_logs')
    op.drop_index('ix_activity_logs_user_id', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('idx_subscription_history_action', table_name='subscription_history')
    op.drop_index('idx_subscription_history_admin_id', table_name='subscription_history')
    op.drop_index('idx_subscription_history_change_date', table_name='subscription_history')
    op.drop_index('idx_subscription_history_tenant_date', table_name='subscription_history')
    op.drop_index('idx_subscription_history_tenant_id', table_name='subscription_history')
    op.drop_table('subscription_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_history',
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False, comment='Tenant ID'),
    sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=True, comment='Admin user who made the change'),
    sa.Column('action', postgresql.ENUM('CREATED', 'UPGRADED', 'DOWNGRADED', 'EXTENDED', 'ACTIVATED', 'DEACTIVATED', 'SUSPENDED', 'RENEWED', 'CANCELLED', name='subscriptionaction'), autoincrement=False, nullable=False, comment='Type of subscription action'),
    sa.Column('old_subscription_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Previous subscription type'),
    sa.Column('new_subscription_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='New subscription type'),
    sa.Column('duration_months', sa.INTEGER(), autoincrement=False, nullable=True, comment='Duration in months (for extensions/renewals)'),
    sa.Column('old_expiry_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Previous expiry date'),
    sa.Column('new_expiry_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='New expiry date'),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True, comment='Reason for the change'),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='Additional notes about the change'),
    sa.Column('change_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='When the change was made'),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True, comment='IP address of admin making change'),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True, comment='User agent of admin making change'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record last update timestamp'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Soft delete flag'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name='subscription_history_admin_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='subscription_history_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subscription_history_pkey')
    )
    op.create_index('idx_subscription_history_tenant_id', 'subscription_history', ['tenant_id'], unique=False)
    op.create_index('idx_subscription_history_tenant_date', 'subscription_history', ['tenant_id', 'change_date'], unique=False)
    op.create_index('idx_subscription_history_change_date', 'subscription_history', ['change_date'], unique=False)
    op.create_index('idx_subscription_history_admin_id', 'subscription_history', ['admin_id'], unique=False)
    op.create_index('idx_subscription_history_action', 'subscription_history', ['action'], unique=False)
    op.create_table('activity_logs',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True, comment='User who performed the action (null for system actions)'),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment="Action type (e.g., 'user_created', 'invoice_updated')"),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment="Type of resource affected (e.g., 'user', 'invoice', 'customer')"),
    sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=True, comment='ID of the affected resource'),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSON object with action details and metadata'),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True, comment='IP address of the request'),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True, comment='User agent string from the request'),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Session identifier'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Action status (success, failed, pending)'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='Error message if action failed'),
    sa.Column('duration_ms', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Action duration in milliseconds'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record last update timestamp'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Soft delete flag'),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False, comment='Tenant ID for multi-tenant data isolation'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='activity_logs_tenant_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='activity_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='activity_logs_pkey')
    )
    op.create_index('ix_activity_logs_user_id', 'activity_logs', ['user_id'], unique=False)
    op.create_index('ix_activity_logs_tenant_id', 'activity_logs', ['tenant_id'], unique=False)
    op.create_index('ix_activity_logs_resource_type', 'activity_logs', ['resource_type'], unique=False)
    op.create_index('ix_activity_logs_resource_id', 'activity_logs', ['resource_id'], unique=False)
    op.create_index('ix_activity_logs_action', 'activity_logs', ['action'], unique=False)
    op.create_index('idx_activity_log_tenant_user', 'activity_logs', ['tenant_id', 'user_id'], unique=False)
    op.create_index('idx_activity_log_tenant_resource', 'activity_logs', ['tenant_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index('idx_activity_log_tenant_date', 'activity_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_activity_log_tenant_action', 'activity_logs', ['tenant_id', 'action'], unique=False)
    op.create_index('idx_activity_log_status', 'activity_logs', ['status'], unique=False)
    op.create_index('idx_activity_log_ip', 'activity_logs', ['ip_address'], unique=False)
    # ### end Alembic commands ###