"""Initial database schema with multi-tenant models and JSONB

Revision ID: efbc6dbd851d
Revises: 
Create Date: 2025-08-31 14:06:53.855313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efbc6dbd851d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_logs', 'storage_locations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='List of storage locations where backup is stored',
               existing_nullable=True)
    op.alter_column('backup_logs', 'backup_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Additional backup metadata',
               existing_nullable=True)
    op.drop_index('idx_customer_tags', table_name='customers', postgresql_using='gin')
    op.alter_column('notification_logs', 'template_variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Variables used in template',
               existing_nullable=True)
    op.alter_column('notification_templates', 'variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Available template variables',
               existing_nullable=True)
    op.drop_index('idx_product_tags', table_name='products', postgresql_using='gin')
    op.alter_column('restore_logs', 'pre_restore_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Snapshot of data before restore',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restore_logs', 'pre_restore_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Snapshot of data before restore',
               existing_nullable=True)
    op.create_index('idx_product_tags', 'products', ['tags'], unique=False, postgresql_using='gin')
    op.alter_column('notification_templates', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Available template variables',
               existing_nullable=True)
    op.alter_column('notification_logs', 'template_variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Variables used in template',
               existing_nullable=True)
    op.create_index('idx_customer_tags', 'customers', ['tags'], unique=False, postgresql_using='gin')
    op.alter_column('backup_logs', 'backup_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Additional backup metadata',
               existing_nullable=True)
    op.alter_column('backup_logs', 'storage_locations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='List of storage locations where backup is stored',
               existing_nullable=True)
    # ### end Alembic commands ###